# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    root: debug
    com.dct.base: debug
  charset:
    console: UTF-8
    file: UTF-8

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true